name: Hyperexecute-Playwright

on:
  push:
    paths-ignore:
      - '**/*.md'  # Adjust this pattern to match the files you want to include/exclude
    branches:
      - main

jobs:
  HyperExecute-Playwright:
    if: contains(github.event.head_commit.message, 'Hyperexecute')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Starting CLI testing
        shell: bash
        run: |
          curl https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute -o hyperexecute
          chmod +x hyperexecute
          ./hyperexecute --user ${{ secrets.username }} --key ${{ secrets.accesskey }} --download-artifacts --config yaml/win/.hyperexecute_autosplits.yaml
          echo "Test completion"
